version: 2.1

jobs:
  build-struts-app:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build Struts App
          command: |
            echo "Files in current directory:"
            ls -al
            echo "Switching to struts-app folder..."
            cd struts-app
            ls -al
            mvn clean package

workflows:
  build-and-deploy:
    jobs:
      - build-struts-app