# .circleci/config.yml

version: 2.1

orbs:
  # Example CircleCI orbs (optional)
  docker: circleci/docker@1.0
  # You could add scanning orbs from Snyk, Anchore, or others

jobs:
  build-struts-app:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build Struts App
          command: |
            cd struts-app
            mvn clean package
      - run:
          name: Build Docker Image
          command: |
            cd struts-app
            docker build -t my-struts-app .
workflows:
  build-and-deploy:
    jobs:
      - build-struts-app
      - build-node-app
      - build-windows-agent