version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Images
          command: |
            # Build Frontend
            docker build -t YOUR_DOCKERHUB_IMAGE/frontend:latest -f frontend/Dockerfile frontend
            # Build Backend
            docker build -t YOUR_DOCKERHUB_IMAGE/backend:latest -f backend/Dockerfile backend

      - run:
          name: Push Docker Images
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push YOUR_DOCKERHUB_IMAGE/frontend:latest
            docker push YOUR_DOCKERHUB_IMAGE/backend:latest

  deploy_to_k8s:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
      - run:
          name: Deploy to Kubernetes
          command: |
            # Decode the KUBECONFIG
            echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig.yaml
            export KUBECONFIG=$(pwd)/kubeconfig.yaml

            # Apply the manifests
            kubectl apply -f deployment/k8s/deployment.yaml
            kubectl apply -f deployment/k8s/service.yaml

workflows:
  build_deploy:
    jobs:
      - build_and_push
      - deploy_to_k8s:
          requires:
            - build_and_push