version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.0
workflows:
  filter-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: main
          mapping: |
            node-app/.* build_node_app true
            struts-app/.* build_struts_app true
            windows-agent/.* build_windows_agent true
            windows-agent.package/.* build_windows_agent true
            ctxcloud.sln build_windows_agent true