version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:lts
  java_executor:
    docker:
      - image: cimg/openjdk:11.0
  windows_executor:
    machine:
      image: windows-server-2019-vs2019:stable

jobs:

  build_node_app:
    executor: node_executor
    working_directory: ~/project/node-app
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - node-deps-{{ checksum "node-app/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Tests
          command: npm test
      - save_cache:
          paths:
            - ~/.npm
          key: node-deps-{{ checksum "node-app/package-lock.json" }}
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t myregistry/ctxcloud-node-app:${CIRCLE_SHA1} .
            docker login -u $DOCKER_USER -p $DOCKER_PASS myregistry.example.com
            docker push myregistry/ctxcloud-node-app:${CIRCLE_SHA1}'
            
workflows:
  ctxcloud_apps_pipeline:
    jobs:
      - build_node_app:
          filters:
            branches:
              only: /.*/
      - build_struts_app:
          filters:
            branches:
              only: /.*/
      - build_windows_agent:
          filters:
            branches:
              only: /.*/