name: PR Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Lint & Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run lint
          npm run build
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install & Test Backend
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          pytest --maxfail=1 --disable-warnings -q